# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# -- Main Menu --

[[main]]
  name = "Blog"
  pageRef = "posts" # Liên kết đến trang liệt kê tất cả bài viết
  weight = 10

[[main]]
  name = "Chủ đề"
  identifier = "chu-de" # Đặt một định danh duy nhất cho mục cha
  weight = 20

[[main]]
  name = "Lập trình Java"
  parent = "chu-de" # Là con của mục "Chủ đề"
  pageRef = "posts/java-beginner" # Trỏ đến trang tổng hợp của series
  weight = 21


[[main]]
  name = "Lập trình JavaScript"
  parent = "chu-de" # Là con của mục "Chủ đề"
  pageRef = "posts/js-beginner" 
  weight = 22

[[main]]
  name = "Về Tôi"
  pageRef = "aboutme.md" # Liên kết đến trang giới thiệu
  weight = 30

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

[[subnavigation]]
  name = "My Awesome Category"
  pre = "github"
  pageRef = "categories/awesome"
  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Categories"
   pageRef = "categories"
   weight = 20
